const translations = {
en: {
navHome:"Home",navServices:"Find Services",navHow:"How to Use",navAwareness:"Health Awareness",navContact:"Contact & Help",
heroEyebrow:"HEALTHCARE, MADE MORE ACCESSIBLE",heroTitle:'Access healthcare with <span>more confidence.</span>',heroText:"Explore online healthcare options, learn how virtual consultations work, and find clear health information in a language you understand.",findCare:"Explore services",howWorks:"How it works",heroNote:"A community education project — not a medical provider.",trust1:"Language-friendly guidance",trust2:"Explore service types",trust3:"Community health awareness",startHere:"START HERE",homeCardsTitle:"Small steps toward digital healthcare",homeCardsText:"Use these guides to understand your options before choosing a real service.",card1Title:"Find a service",card1Text:"Explore common types of healthcare professionals and what they can help with.",learnMore:"Explore services →",card2Title:"Learn the steps",card2Text:"A simple guide to preparing for an online appointment, even if it is your first time.",readGuide:"Read the guide →",card3Title:"Build health awareness",card3Text:"Read basic, general information and learn when professional advice matters.",browseTips:"Browse health tips →",needHelp:"NEED A LITTLE HELP?",calloutTitle:"Technology should feel simpler, not harder.",calloutText:"Ask a trusted family member or community health worker to help you connect safely.",getHelp:"Get help",important:"Important health note",disclaimerText:"CareConnect is an educational demonstration website. It does not diagnose conditions, provide treatment, book real doctors, or monitor emergencies. For urgent medical help in India, call 112 or go to the nearest emergency department.",footerText:"Healthcare information should be understandable and accessible to everyone.",
serviceEyebrow:"EXPLORE YOUR OPTIONS",serviceTitle:"Find the kind of care you need",serviceIntro:"Search these educational service categories by specialty or keyword. This demo does not verify providers or make bookings.",searchLabel:"Search by specialty or keyword",searchPlaceholder:"Try “children”, “general”, or “wellbeing”",clear:"Clear",generalTitle:"General physician",generalText:"For general health concerns, routine advice, and guidance on whether further care is needed.",generalTag:"Primary care",childTitle:"Child specialist",childText:"For children's health, growth, development, and age-appropriate care questions.",childTag:"Children's health",womenTitle:"Women's health",womenText:"For reproductive health questions, menstrual concerns, and pregnancy-related guidance.",womenTag:"Women's wellness",mentalTitle:"Mental wellbeing",mentalText:"For emotional wellbeing, stress management, and finding appropriate professional support.",mentalTag:"Wellbeing",chronicTitle:"Long-term conditions",chronicText:"For follow-up discussions about ongoing conditions with a qualified clinician.",chronicTag:"Follow-up care",nutritionTitle:"Nutrition guidance",nutritionText:"For general food, balanced diet, and nutrition questions with a qualified professional.",nutritionTag:"Healthy living",noResults:"No matching categories found",tryAnother:"Try a different word or clear your search.",beforeBooking:"BEFORE YOU BOOK",beforeTitle:"Check the provider is qualified",beforeText:"Confirm registration, fees, privacy practices, and whether online consultation is suitable. Use a trusted healthcare provider or official service.",prepareVisit:"Prepare for a visit",appointmentEyebrow:"PRACTISE THE PROCESS",appointmentTitle:"Try a demo appointment request",appointmentText:"This sample form demonstrates what an appointment request could look like. It does not contact a doctor or book a real appointment.",appointmentName:"Your name",appointmentService:"Service category",chooseService:"Choose a service",appointmentDate:"Preferred date",requestAppointment:"Request demo appointment →",appointmentConfirmTitle:"Demo request received!",close:"Close",
howEyebrow:"YOUR FIRST ONLINE CONSULTATION",howTitle:"One step at a time",howIntro:"You do not need to be a technology expert. Ask someone you trust to help if you need it.",step1Title:"Choose a trusted service",step1Text:"Use an official healthcare website or app. Check the provider's credentials, consultation fees, and privacy policy.",step2Title:"Select your language",step2Text:"Choose a language you understand. Ask whether the clinician can communicate in that language before confirming.",step3Title:"Prepare your information",step3Text:"Write down your questions, current medicines, allergies, and relevant health history. Share only what is needed through a secure service.",step4Title:"Join the consultation",step4Text:"Find a quiet, private place and test your phone, internet, camera, or microphone. Follow the provider's official instructions.",step5Title:"Review next steps",step5Text:"Ask questions if something is unclear. Confirm any follow-up plan and where to get help if your condition worsens.",safetyFirst:"SAFETY FIRST",privacyTitle:"Protect your privacy",privacy1:"Use a trusted device and a private connection where possible.",privacy2:"Never share passwords or one-time codes with someone claiming to be a doctor.",privacy3:"Check the website address and avoid unknown payment links.",privacy4:"A remote consultation may not be appropriate for every problem.",lowInternet:"LOW INTERNET ACCESS?",lowTitle:"You still have options",lowText:"Ask a local health worker about nearby public health facilities, telemedicine assistance, or a phone consultation. Do not delay urgent care while trying to connect online.",helpOptions:"View help options →",demoOnly:"Demonstration only",demoText:"These steps are educational. This website does not initiate video calls, send messages to doctors, or create real appointments.",
awarenessEyebrow:"LEARN · ASK · TAKE CARE",awarenessTitle:"Everyday health awareness",awarenessIntro:"Short, general learning notes to help you have better conversations with qualified health professionals.",generalInfo:"GENERAL INFORMATION",feverTitle:"Fever and common illness",feverText:"Rest and fluids may help with comfort, but fever can have many causes. Seek medical advice if symptoms are concerning, persistent, or worsening.",readMore:"Read more",feverMore:"Record the temperature if you can, note other symptoms and how long they have lasted, and tell a clinician about medicines already taken. Seek urgent help for severe symptoms such as difficulty breathing, confusion, or becoming difficult to wake.",longTermInfo:"LONG-TERM HEALTH",diabetesTitle:"Diabetes awareness",diabetesText:"Diabetes care may include health checks, medicines when prescribed, balanced eating, activity suited to the person, and regular follow-up.",diabetesMore:"Only a qualified health professional can assess your needs. Do not start, stop, or change prescribed medicine based on a website. Ask about appropriate blood glucose testing and follow-up.",wellnessInfo:"WELLNESS",hygieneTitle:"Menstrual and personal hygiene",hygieneText:"Use clean menstrual products, change them regularly according to product guidance, and wash hands before and after changing.",hygieneMore:"Choose products that are safe and comfortable for you. Seek advice from a health professional if you have severe pain, unusually heavy bleeding, fever, or other worrying symptoms.",wellbeingInfo:"WELLBEING",mentalAwarenessTitle:"Stress and mental wellbeing",mentalAwarenessText:"Sleep, supportive relationships, regular routines, and calming activities can support wellbeing. It is okay to ask for help.",mentalMore:"If stress or low mood affects daily life, consider talking with a qualified professional or trusted person. If someone is in immediate danger, contact local emergency services.",remember:"REMEMBER",awarenessCalloutTitle:"Online information is a starting point",awarenessCalloutText:"It cannot replace individual medical advice, diagnosis, or emergency care.",exploreCare:"Explore care options",
contactEyebrow:"WE ARE HERE TO GUIDE YOU",contactTitle:"Contact and help",contactIntro:"Use this demo form to practise sharing feedback. It does not send or store your message.",sendMessage:"Send a message",formNote:"Please do not include medical records, passwords, or private health details.",nameLabel:"Your name (optional)",emailLabel:"Email (optional)",topicLabel:"What is your message about?",chooseTopic:"Choose a topic",topicFeedback:"Website feedback",topicAccess:"Accessing online healthcare",topicProject:"College project",topicOther:"Other",messageLabel:"Message",submitMessage:"Submit demo message →",emergencyTitle:"Emergency in India",emergencyText:"For an immediate emergency, call India's pan-India emergency number.",emergencyNote:"This is not a CareConnect hotline. Do not use email or this demo form for emergencies.",communityHelpTitle:"Need help using a phone?",communityHelpText:"Ask a trusted family member, community health worker, or staff at a nearby public health facility for help finding official services.",privacyHelpTitle:"Stay safe online",privacyHelpText:"Never share your password or one-time password. Verify the provider and payment details before proceeding."
},
hi: {
navHome:"होम",navServices:"सेवाएँ खोजें",navHow:"उपयोग कैसे करें",navAwareness:"स्वास्थ्य जागरूकता",navContact:"संपर्क और सहायता",
heroEyebrow:"स्वास्थ्य सेवाएँ, अब और आसान",heroTitle:'अधिक भरोसे के साथ <span>स्वास्थ्य सेवाएँ पाएँ।</span>',heroText:"ऑनलाइन स्वास्थ्य सेवाओं के विकल्प जानें, वीडियो परामर्श समझें और अपनी भाषा में स्वास्थ्य जानकारी पढ़ें।",findCare:"सेवाएँ देखें",howWorks:"कैसे काम करता है",heroNote:"यह सामुदायिक शिक्षा परियोजना है, चिकित्सा सेवा प्रदाता नहीं।",trust1:"अपनी भाषा में मार्गदर्शन",trust2:"सेवाओं के प्रकार जानें",trust3:"सामुदायिक स्वास्थ्य जागरूकता",startHere:"यहाँ से शुरू करें",homeCardsTitle:"डिजिटल स्वास्थ्य सेवा की ओर छोटे कदम",homeCardsText:"वास्तविक सेवा चुनने से पहले इन मार्गदर्शिकाओं से विकल्प समझें।",card1Title:"सेवा खोजें",card1Text:"स्वास्थ्य विशेषज्ञों के प्रकार और उनकी मदद के बारे में जानें।",learnMore:"सेवाएँ देखें →",card2Title:"कदम जानें",card2Text:"पहली बार भी ऑनलाइन परामर्श की तैयारी के लिए सरल मार्गदर्शिका।",readGuide:"मार्गदर्शिका पढ़ें →",card3Title:"स्वास्थ्य जागरूकता",card3Text:"सामान्य जानकारी पढ़ें और जानें कि विशेषज्ञ की सलाह कब ज़रूरी है।",browseTips:"स्वास्थ्य सुझाव देखें →",needHelp:"थोड़ी मदद चाहिए?",calloutTitle:"तकनीक आसान लगनी चाहिए, मुश्किल नहीं।",calloutText:"सुरक्षित रूप से जुड़ने के लिए परिवार के भरोसेमंद सदस्य या स्वास्थ्य कार्यकर्ता से मदद लें।",getHelp:"मदद पाएँ",important:"स्वास्थ्य संबंधी ज़रूरी सूचना",disclaimerText:"CareConnect एक शैक्षिक प्रदर्शन वेबसाइट है। यह बीमारी की जाँच, इलाज, वास्तविक डॉक्टर की बुकिंग या आपातकालीन निगरानी नहीं करती। भारत में तत्काल चिकित्सा सहायता के लिए 112 पर कॉल करें या नज़दीकी आपातकालीन विभाग जाएँ।",footerText:"स्वास्थ्य जानकारी सभी के लिए समझने योग्य और सुलभ होनी चाहिए।",
serviceEyebrow:"अपने विकल्प जानें",serviceTitle:"अपनी ज़रूरत के अनुसार सेवा खोजें",serviceIntro:"विशेषज्ञता या शब्द के आधार पर इन शैक्षिक सेवा श्रेणियों को खोजें। यह डेमो प्रदाताओं की पुष्टि या बुकिंग नहीं करता।",searchLabel:"विशेषज्ञता या शब्द से खोजें",searchPlaceholder:"“बच्चे”, “सामान्य” या “मानसिक स्वास्थ्य” आज़माएँ",clear:"साफ़ करें",generalTitle:"सामान्य चिकित्सक",generalText:"सामान्य स्वास्थ्य समस्याओं, नियमित सलाह और आगे की देखभाल के मार्गदर्शन के लिए।",generalTag:"प्राथमिक देखभाल",childTitle:"बाल रोग विशेषज्ञ",childText:"बच्चों के स्वास्थ्य, विकास और उम्र के अनुसार देखभाल संबंधी प्रश्नों के लिए।",childTag:"बच्चों का स्वास्थ्य",womenTitle:"महिला स्वास्थ्य",womenText:"प्रजनन स्वास्थ्य, मासिक धर्म और गर्भावस्था संबंधी मार्गदर्शन के लिए।",womenTag:"महिला कल्याण",mentalTitle:"मानसिक स्वास्थ्य",mentalText:"भावनात्मक स्वास्थ्य, तनाव प्रबंधन और पेशेवर सहायता खोजने के लिए।",mentalTag:"मानसिक कल्याण",chronicTitle:"दीर्घकालिक बीमारियाँ",chronicText:"लगातार चल रही स्वास्थ्य समस्याओं के लिए योग्य चिकित्सक से फॉलो-अप।",chronicTag:"फॉलो-अप देखभाल",nutritionTitle:"पोषण संबंधी मार्गदर्शन",nutritionText:"संतुलित आहार और पोषण संबंधी प्रश्नों के लिए योग्य विशेषज्ञ से सलाह।",nutritionTag:"स्वस्थ जीवन",noResults:"कोई मिलती-जुलती श्रेणी नहीं मिली",tryAnother:"दूसरा शब्द आज़माएँ या खोज साफ़ करें।",beforeBooking:"बुकिंग से पहले",beforeTitle:"प्रदाता की योग्यता जाँचें",beforeText:"पंजीकरण, शुल्क, गोपनीयता नीति और ऑनलाइन परामर्श की उपयुक्तता की पुष्टि करें। भरोसेमंद या आधिकारिक सेवा चुनें।",prepareVisit:"परामर्श की तैयारी करें",
howEyebrow:"आपका पहला ऑनलाइन परामर्श",howTitle:"एक-एक कदम करके",howIntro:"तकनीक के विशेषज्ञ होना ज़रूरी नहीं। ज़रूरत पड़ने पर किसी भरोसेमंद व्यक्ति से मदद लें।",step1Title:"भरोसेमंद सेवा चुनें",step1Text:"आधिकारिक स्वास्थ्य वेबसाइट या ऐप इस्तेमाल करें। प्रदाता की योग्यता, शुल्क और गोपनीयता नीति जाँचें।",step2Title:"अपनी भाषा चुनें",step2Text:"ऐसी भाषा चुनें जिसे आप समझते हैं। पुष्टि करने से पहले पूछें कि चिकित्सक उस भाषा में बात कर सकते हैं या नहीं।",step3Title:"जानकारी तैयार रखें",step3Text:"अपने प्रश्न, मौजूदा दवाएँ, एलर्जी और संबंधित स्वास्थ्य इतिहास लिखें। सुरक्षित सेवा पर केवल ज़रूरी जानकारी साझा करें।",step4Title:"परामर्श में जुड़ें",step4Text:"शांत और निजी जगह चुनें। फ़ोन, इंटरनेट, कैमरा और माइक्रोफ़ोन जाँचें। आधिकारिक निर्देशों का पालन करें।",step5Title:"अगले कदम समझें",step5Text:"कुछ स्पष्ट न हो तो प्रश्न पूछें। आगे की योजना और हालत बिगड़ने पर मदद कहाँ मिलेगी, इसकी पुष्टि करें।",safetyFirst:"सबसे पहले सुरक्षा",privacyTitle:"अपनी गोपनीयता सुरक्षित रखें",privacy1:"जहाँ संभव हो भरोसेमंद डिवाइस और निजी कनेक्शन इस्तेमाल करें।",privacy2:"डॉक्टर होने का दावा करने वाले किसी व्यक्ति से पासवर्ड या OTP साझा न करें।",privacy3:"वेबसाइट का पता जाँचें और अनजान भुगतान लिंक से बचें।",privacy4:"हर समस्या के लिए दूरस्थ परामर्श उपयुक्त नहीं होता।",lowInternet:"इंटरनेट कमज़ोर है?",lowTitle:"आपके पास दूसरे विकल्प भी हैं",lowText:"नज़दीकी सरकारी स्वास्थ्य केंद्र, टेलीमेडिसिन सहायता या फ़ोन परामर्श के बारे में स्थानीय स्वास्थ्य कार्यकर्ता से पूछें। ऑनलाइन जुड़ने के प्रयास में ज़रूरी इलाज में देरी न करें।",helpOptions:"सहायता विकल्प देखें →",demoOnly:"केवल प्रदर्शन",demoText:"ये शैक्षिक चरण हैं। यह वेबसाइट वीडियो कॉल शुरू नहीं करती, डॉक्टर को संदेश नहीं भेजती और वास्तविक अपॉइंटमेंट नहीं बनाती।",
awarenessEyebrow:"सीखें · पूछें · ध्यान रखें",awarenessTitle:"रोज़मर्रा की स्वास्थ्य जागरूकता",awarenessIntro:"योग्य स्वास्थ्य विशेषज्ञ से बेहतर बातचीत करने के लिए छोटी सामान्य जानकारी।",generalInfo:"सामान्य जानकारी",feverTitle:"बुखार और आम बीमारी",feverText:"आराम और तरल पदार्थ आराम दे सकते हैं, लेकिन बुखार के कई कारण होते हैं। लक्षण गंभीर, लगातार या बिगड़ रहे हों तो चिकित्सा सलाह लें।",readMore:"और पढ़ें",feverMore:"संभव हो तो तापमान और अन्य लक्षणों की अवधि लिखें। ली गई दवाओं के बारे में चिकित्सक को बताएँ। साँस लेने में कठिनाई, भ्रम या जगाने में कठिनाई जैसे गंभीर लक्षणों पर तुरंत मदद लें।",longTermInfo:"दीर्घकालिक स्वास्थ्य",diabetesTitle:"मधुमेह जागरूकता",diabetesText:"मधुमेह की देखभाल में जाँच, निर्धारित दवाएँ, संतुलित भोजन, व्यक्ति के अनुसार गतिविधि और नियमित फॉलो-अप शामिल हो सकते हैं।",diabetesMore:"आपकी ज़रूरत का आकलन केवल योग्य स्वास्थ्य विशेषज्ञ कर सकता है। वेबसाइट के आधार पर निर्धारित दवा शुरू, बंद या बदलें नहीं।",wellnessInfo:"स्वास्थ्य और स्वच्छता",hygieneTitle:"मासिक धर्म और व्यक्तिगत स्वच्छता",hygieneText:"साफ़ मासिक धर्म उत्पाद इस्तेमाल करें, निर्देशों के अनुसार नियमित बदलें और बदलने से पहले व बाद में हाथ धोएँ।",hygieneMore:"अपने लिए सुरक्षित और आरामदायक उत्पाद चुनें। तेज़ दर्द, बहुत अधिक रक्तस्राव, बुखार या अन्य चिंताजनक लक्षण हों तो स्वास्थ्य विशेषज्ञ से सलाह लें।",wellbeingInfo:"मानसिक कल्याण",mentalAwarenessTitle:"तनाव और मानसिक स्वास्थ्य",mentalAwarenessText:"नींद, सहायक रिश्ते, नियमित दिनचर्या और शांत करने वाली गतिविधियाँ मदद कर सकती हैं। मदद माँगना ठीक है।",mentalMore:"तनाव या उदासी रोज़मर्रा की ज़िंदगी को प्रभावित करे तो योग्य विशेषज्ञ या भरोसेमंद व्यक्ति से बात करें। तत्काल खतरे में स्थानीय आपातकालीन सेवा से संपर्क करें।",remember:"याद रखें",awarenessCalloutTitle:"ऑनलाइन जानकारी बस शुरुआत है",awarenessCalloutText:"यह व्यक्तिगत चिकित्सा सलाह, निदान या आपातकालीन देखभाल का विकल्प नहीं है।",exploreCare:"सेवा विकल्प देखें",
contactEyebrow:"हम मार्गदर्शन के लिए यहाँ हैं",contactTitle:"संपर्क और सहायता",contactIntro:"प्रतिक्रिया देने का अभ्यास करने के लिए यह डेमो फ़ॉर्म इस्तेमाल करें। संदेश भेजा या सहेजा नहीं जाता।",sendMessage:"संदेश लिखें",formNote:"चिकित्सा रिकॉर्ड, पासवर्ड या निजी स्वास्थ्य विवरण न लिखें।",nameLabel:"आपका नाम (वैकल्पिक)",emailLabel:"ईमेल (वैकल्पिक)",topicLabel:"संदेश किस बारे में है?",chooseTopic:"विषय चुनें",topicFeedback:"वेबसाइट प्रतिक्रिया",topicAccess:"ऑनलाइन स्वास्थ्य सेवा तक पहुँच",topicProject:"कॉलेज प्रोजेक्ट",topicOther:"अन्य",messageLabel:"संदेश",submitMessage:"डेमो संदेश जमा करें →",emergencyTitle:"भारत में आपातकाल",emergencyText:"तत्काल आपात स्थिति में भारत के राष्ट्रीय आपातकालीन नंबर पर कॉल करें।",emergencyNote:"यह CareConnect हेल्पलाइन नहीं है। आपात स्थिति में ईमेल या इस डेमो फ़ॉर्म का उपयोग न करें।",communityHelpTitle:"फ़ोन इस्तेमाल करने में मदद चाहिए?",communityHelpText:"आधिकारिक सेवा खोजने के लिए परिवार के भरोसेमंद सदस्य, सामुदायिक स्वास्थ्य कार्यकर्ता या नज़दीकी सरकारी स्वास्थ्य केंद्र के कर्मचारी से मदद लें।",privacyHelpTitle:"ऑनलाइन सुरक्षित रहें",privacyHelpText:"अपना पासवर्ड या OTP साझा न करें। आगे बढ़ने से पहले प्रदाता और भुगतान विवरण की पुष्टि करें।"
},
mr: {
navHome:"मुख्यपृष्ठ",navServices:"सेवा शोधा",navHow:"वापर कसा करावा",navAwareness:"आरोग्य जागरूकता",navContact:"संपर्क व मदत",
heroEyebrow:"आरोग्यसेवा, अधिक सहजपणे",heroTitle:'अधिक आत्मविश्वासाने <span>आरोग्यसेवा मिळवा.</span>',heroText:"ऑनलाइन आरोग्यसेवेचे पर्याय जाणून घ्या, व्हर्च्युअल सल्लामसलत कशी होते ते समजून घ्या आणि आपल्या भाषेत आरोग्यविषयक माहिती वाचा.",findCare:"सेवा पाहा",howWorks:"हे कसे कार्य करते",heroNote:"हा सामुदायिक शिक्षण प्रकल्प आहे; वैद्यकीय सेवा प्रदाता नाही.",trust1:"आपल्या भाषेत मार्गदर्शन",trust2:"सेवांचे प्रकार जाणून घ्या",trust3:"सामुदायिक आरोग्य जागरूकता",startHere:"येथून सुरुवात करा",homeCardsTitle:"डिजिटल आरोग्यसेवेकडे छोटी पावले",homeCardsText:"प्रत्यक्ष सेवा निवडण्यापूर्वी हे मार्गदर्शक वापरून पर्याय समजून घ्या.",card1Title:"सेवा शोधा",card1Text:"आरोग्यतज्ज्ञांचे प्रकार आणि ते कशी मदत करू शकतात हे जाणून घ्या.",learnMore:"सेवा पाहा →",card2Title:"पायऱ्या समजून घ्या",card2Text:"पहिल्यांदाही ऑनलाइन भेटीची तयारी करण्यासाठी सोपे मार्गदर्शन.",readGuide:"मार्गदर्शक वाचा →",card3Title:"आरोग्य जागरूकता वाढवा",card3Text:"सामान्य माहिती वाचा आणि तज्ज्ञांचा सल्ला कधी आवश्यक आहे ते जाणून घ्या.",browseTips:"आरोग्य टिप्स पाहा →",needHelp:"थोडी मदत हवी आहे?",calloutTitle:"तंत्रज्ञान सोपे वाटायला हवे, अवघड नाही.",calloutText:"सुरक्षितपणे जोडण्यासाठी विश्वासू कुटुंबीय किंवा सामुदायिक आरोग्य कर्मचाऱ्याची मदत घ्या.",getHelp:"मदत मिळवा",important:"आरोग्यविषयक महत्त्वाची सूचना",disclaimerText:"CareConnect ही शैक्षणिक प्रात्यक्षिक वेबसाइट आहे. ती निदान, उपचार, प्रत्यक्ष डॉक्टरांची बुकिंग किंवा आपत्कालीन देखरेख करत नाही. भारतात तातडीच्या वैद्यकीय मदतीसाठी 112 वर कॉल करा किंवा जवळच्या आपत्कालीन विभागात जा.",footerText:"आरोग्यविषयक माहिती सर्वांना समजण्यास सोपी आणि उपलब्ध असावी.",
serviceEyebrow:"आपले पर्याय जाणून घ्या",serviceTitle:"आपल्याला आवश्यक असलेली सेवा शोधा",serviceIntro:"विशेषज्ञता किंवा शब्द वापरून या शैक्षणिक सेवा श्रेणी शोधा. हे डेमो सेवा प्रदात्यांची पडताळणी किंवा बुकिंग करत नाही.",searchLabel:"विशेषज्ञता किंवा शब्दाने शोधा",searchPlaceholder:"“मुले”, “सामान्य” किंवा “मानसिक आरोग्य” वापरून पाहा",clear:"पुसून टाका",generalTitle:"सामान्य वैद्यकीय तज्ज्ञ",generalText:"सामान्य आरोग्य समस्या, नियमित सल्ला आणि पुढील काळजीबाबत मार्गदर्शनासाठी.",generalTag:"प्राथमिक काळजी",childTitle:"बालरोगतज्ज्ञ",childText:"मुलांचे आरोग्य, वाढ, विकास आणि वयानुसार काळजीविषयक प्रश्नांसाठी.",childTag:"बालआरोग्य",womenTitle:"महिला आरोग्य",womenText:"प्रजनन आरोग्य, मासिक पाळी आणि गर्भधारणेसंबंधी मार्गदर्शनासाठी.",womenTag:"महिला कल्याण",mentalTitle:"मानसिक आरोग्य",mentalText:"भावनिक स्वास्थ्य, तणाव व्यवस्थापन आणि योग्य व्यावसायिक मदत शोधण्यासाठी.",mentalTag:"मानसिक स्वास्थ्य",chronicTitle:"दीर्घकालीन आजार",chronicText:"सुरू असलेल्या आरोग्य समस्यांबाबत पात्र डॉक्टरांसोबत पुढील सल्ल्यासाठी.",chronicTag:"पुढील तपासणी",nutritionTitle:"पोषणविषयक मार्गदर्शन",nutritionText:"संतुलित आहार आणि पोषणविषयक प्रश्नांसाठी पात्र तज्ज्ञांचा सल्ला.",nutritionTag:"निरोगी जीवन",noResults:"जुळणाऱ्या श्रेणी सापडल्या नाहीत",tryAnother:"दुसरा शब्द वापरा किंवा शोध पुसून टाका.",beforeBooking:"बुकिंग करण्यापूर्वी",beforeTitle:"सेवा प्रदात्याची पात्रता तपासा",beforeText:"नोंदणी, शुल्क, गोपनीयता धोरण आणि ऑनलाइन सल्ला योग्य आहे का ते तपासा. विश्वासार्ह किंवा अधिकृत सेवा वापरा.",prepareVisit:"भेटीची तयारी करा",appointmentEyebrow:"प्रक्रियेचा सराव करा",appointmentTitle:"डेमो अपॉइंटमेंट विनंती करून पाहा",appointmentText:"या नमुना फॉर्ममधून विनंती कशी दिसू शकते ते समजते. यामुळे डॉक्टरांशी संपर्क किंवा प्रत्यक्ष बुकिंग होत नाही.",appointmentName:"आपले नाव",appointmentService:"सेवेची श्रेणी",chooseService:"सेवा निवडा",appointmentDate:"पसंतीची तारीख",requestAppointment:"डेमो अपॉइंटमेंटची विनंती करा →",appointmentConfirmTitle:"डेमो विनंती प्राप्त झाली!",close:"बंद करा",
howEyebrow:"तुमची पहिली ऑनलाइन सल्लामसलत",howTitle:"एकावेळी एक पाऊल",howIntro:"तंत्रज्ञानात तज्ज्ञ असण्याची गरज नाही. गरज असल्यास विश्वासू व्यक्तीची मदत घ्या.",step1Title:"विश्वासार्ह सेवा निवडा",step1Text:"अधिकृत आरोग्य वेबसाइट किंवा अॅप वापरा. प्रदात्याची पात्रता, शुल्क आणि गोपनीयता धोरण तपासा.",step2Title:"आपली भाषा निवडा",step2Text:"आपल्याला समजणारी भाषा निवडा. निश्चित करण्यापूर्वी डॉक्टर त्या भाषेत बोलू शकतात का ते विचारा.",step3Title:"माहिती तयार ठेवा",step3Text:"प्रश्न, सध्या घेत असलेली औषधे, अॅलर्जी आणि संबंधित आरोग्य इतिहास लिहून ठेवा. सुरक्षित सेवेत आवश्यक तेवढीच माहिती द्या.",step4Title:"सल्लामसलतीत सहभागी व्हा",step4Text:"शांत आणि खाजगी जागा निवडा. फोन, इंटरनेट, कॅमेरा आणि मायक्रोफोन तपासा. अधिकृत सूचनांचे पालन करा.",step5Title:"पुढील पावले समजून घ्या",step5Text:"काही अस्पष्ट असल्यास प्रश्न विचारा. पुढील योजना आणि प्रकृती बिघडल्यास मदत कुठे मिळेल हे जाणून घ्या.",safetyFirst:"सुरक्षा सर्वात आधी",privacyTitle:"आपली गोपनीयता जपा",privacy1:"शक्य असल्यास विश्वासार्ह उपकरण आणि खाजगी कनेक्शन वापरा.",privacy2:"डॉक्टर असल्याचा दावा करणाऱ्या व्यक्तीला पासवर्ड किंवा OTP देऊ नका.",privacy3:"वेबसाइटचा पत्ता तपासा आणि अनोळखी पेमेंट लिंक टाळा.",privacy4:"प्रत्येक समस्येसाठी दूरस्थ सल्लामसलत योग्य असेलच असे नाही.",lowInternet:"इंटरनेट कमी आहे?",lowTitle:"आपल्याकडे इतर पर्याय आहेत",lowText:"जवळचे सार्वजनिक आरोग्य केंद्र, टेलिमेडिसिन मदत किंवा फोनवरील सल्ल्याबद्दल स्थानिक आरोग्य कर्मचाऱ्याला विचारा. ऑनलाइन जोडण्याच्या प्रयत्नात तातडीच्या उपचारांना उशीर करू नका.",helpOptions:"मदतीचे पर्याय पाहा →",demoOnly:"फक्त प्रात्यक्षिक",demoText:"या शैक्षणिक सूचना आहेत. ही वेबसाइट व्हिडिओ कॉल सुरू करत नाही, डॉक्टरांना संदेश पाठवत नाही किंवा प्रत्यक्ष भेटीची वेळ नोंदवत नाही.",
awarenessEyebrow:"शिका · विचारा · काळजी घ्या",awarenessTitle:"दैनंदिन आरोग्य जागरूकता",awarenessIntro:"पात्र आरोग्यतज्ज्ञांशी चांगला संवाद साधण्यासाठी थोडक्यात सामान्य माहिती.",generalInfo:"सामान्य माहिती",feverTitle:"ताप आणि सामान्य आजार",feverText:"विश्रांती आणि द्रवपदार्थांमुळे आराम मिळू शकतो; मात्र तापाची अनेक कारणे असतात. लक्षणे गंभीर, दीर्घकाळ टिकणारी किंवा वाढत असल्यास वैद्यकीय सल्ला घ्या.",readMore:"अधिक वाचा",feverMore:"शक्य असल्यास तापमान आणि इतर लक्षणे किती काळ आहेत ते नोंदवा. घेतलेल्या औषधांबद्दल डॉक्टरांना सांगा. श्वास घेण्यास त्रास, गोंधळ किंवा जागे करणे कठीण होणे यांसारखी गंभीर लक्षणे असल्यास तातडीने मदत घ्या.",longTermInfo:"दीर्घकालीन आरोग्य",diabetesTitle:"मधुमेह जागरूकता",diabetesText:"मधुमेहाच्या काळजीमध्ये आरोग्य तपासणी, लिहून दिलेली औषधे, संतुलित आहार, योग्य शारीरिक हालचाल आणि नियमित पाठपुरावा यांचा समावेश असू शकतो.",diabetesMore:"आपल्या गरजांचे मूल्यांकन फक्त पात्र आरोग्यतज्ज्ञ करू शकतात. वेबसाइट पाहून डॉक्टरांनी दिलेली औषधे सुरू, बंद किंवा बदलू नका.",wellnessInfo:"आरोग्य आणि स्वच्छता",hygieneTitle:"मासिक पाळी आणि वैयक्तिक स्वच्छता",hygieneText:"स्वच्छ मासिक पाळीची उत्पादने वापरा, सूचनांनुसार नियमित बदला आणि बदलण्यापूर्वी व नंतर हात धुवा.",hygieneMore:"आपल्यासाठी सुरक्षित आणि आरामदायक उत्पादने निवडा. तीव्र वेदना, असामान्यपणे जास्त रक्तस्राव, ताप किंवा इतर चिंताजनक लक्षणे असल्यास आरोग्यतज्ज्ञांचा सल्ला घ्या.",wellbeingInfo:"मानसिक स्वास्थ्य",mentalAwarenessTitle:"तणाव आणि मानसिक स्वास्थ्य",mentalAwarenessText:"झोप, आधार देणारे नातेसंबंध, नियमित दिनक्रम आणि शांत करणाऱ्या कृती स्वास्थ्यासाठी मदत करू शकतात. मदत मागणे योग्य आहे.",mentalMore:"तणाव किंवा खिन्नतेचा दैनंदिन जीवनावर परिणाम होत असल्यास पात्र तज्ज्ञ किंवा विश्वासू व्यक्तीशी बोला. तातडीचा धोका असल्यास स्थानिक आपत्कालीन सेवेशी संपर्क साधा.",remember:"लक्षात ठेवा",awarenessCalloutTitle:"ऑनलाइन माहिती ही फक्त सुरुवात आहे",awarenessCalloutText:"ती वैयक्तिक वैद्यकीय सल्ला, निदान किंवा आपत्कालीन उपचारांची जागा घेऊ शकत नाही.",exploreCare:"सेवेचे पर्याय पाहा",
contactEyebrow:"मार्गदर्शनासाठी आम्ही येथे आहोत",contactTitle:"संपर्क आणि मदत",contactIntro:"अभिप्राय देण्याचा सराव करण्यासाठी हा डेमो फॉर्म वापरा. संदेश पाठवला किंवा जतन केला जात नाही.",sendMessage:"संदेश लिहा",formNote:"वैद्यकीय नोंदी, पासवर्ड किंवा खाजगी आरोग्यविषयक तपशील लिहू नका.",nameLabel:"आपले नाव (ऐच्छिक)",emailLabel:"ईमेल (ऐच्छिक)",topicLabel:"संदेश कशाबद्दल आहे?",chooseTopic:"विषय निवडा",topicFeedback:"वेबसाइट अभिप्राय",topicAccess:"ऑनलाइन आरोग्यसेवा मिळवणे",topicProject:"महाविद्यालयीन प्रकल्प",topicOther:"इतर",messageLabel:"संदेश",submitMessage:"डेमो संदेश सादर करा →",emergencyTitle:"भारतातील आपत्कालीन मदत",emergencyText:"तातडीच्या आपत्कालीन परिस्थितीत भारताच्या राष्ट्रीय आपत्कालीन क्रमांकावर कॉल करा.",emergencyNote:"हा CareConnect हेल्पलाइन क्रमांक नाही. आपत्कालीन परिस्थितीत ईमेल किंवा हा डेमो फॉर्म वापरू नका.",communityHelpTitle:"फोन वापरण्यास मदत हवी आहे?",communityHelpText:"अधिकृत सेवा शोधण्यासाठी विश्वासू कुटुंबीय, सामुदायिक आरोग्य कर्मचारी किंवा जवळच्या सार्वजनिक आरोग्य केंद्रातील कर्मचाऱ्यांची मदत घ्या.",privacyHelpTitle:"ऑनलाइन सुरक्षित राहा",privacyHelpText:"पासवर्ड किंवा OTP कोणालाही देऊ नका. पुढे जाण्यापूर्वी सेवा प्रदाता आणि पेमेंट तपशील तपासा."
}
};
function setLanguage(lang) {
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang === "hi" ? "hi" : lang === "mr" ? "mr" : "en";
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key] !== undefined) el.innerHTML = dict[key];
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (dict[key] !== undefined) el.placeholder = dict[key];
  });
  document.querySelectorAll("#languageSelect").forEach(select => select.value = lang);
  try { localStorage.setItem("careconnect-language", lang); } catch (_) {}
  updateSearchCount();
}
function updateSearchCount() {
  const input = document.getElementById("serviceSearch");
  if (!input) return;
  const cards = [...document.querySelectorAll(".service-card")];
  const query = input.value.trim().toLocaleLowerCase();
  let count = 0;
  cards.forEach(card => {
    const text = (card.innerText + " " + card.dataset.search).toLocaleLowerCase();
    const visible = !query || text.includes(query);
    card.hidden = !visible;
    if (visible) count++;
  });
  const countNode = document.getElementById("resultsCount");
  const lang = document.getElementById("languageSelect")?.value || "en";
  if (countNode) {
    const label = lang === "hi" ? `दिखाई गई श्रेणियाँ: ${count}` : lang === "mr" ? `दिसणाऱ्या श्रेणी: ${count}` : `Showing ${count} ${count === 1 ? "category" : "categories"}`;
    countNode.textContent = label;
  }
  const empty = document.getElementById("emptyState");
  if (empty) empty.hidden = count !== 0;
}
document.addEventListener("DOMContentLoaded", () => {
  const languageSelects = document.querySelectorAll("#languageSelect");
  let saved = "en";
  try { saved = localStorage.getItem("careconnect-language") || "en"; } catch (_) {}
  languageSelects.forEach(select => {
    select.addEventListener("change", event => setLanguage(event.target.value));
  });
  setLanguage(saved);
  const toggle = document.getElementById("menuToggle");
  const nav = document.getElementById("mainNav");
  if (toggle && nav) toggle.addEventListener("click", () => {
    const open = nav.classList.toggle("open");
    toggle.setAttribute("aria-expanded", String(open));
  });
  const search = document.getElementById("serviceSearch");
  if (search) {
    search.addEventListener("input", updateSearchCount);
    document.getElementById("clearSearch")?.addEventListener("click", () => {
      search.value = "";
      updateSearchCount();
      search.focus();
    });
    updateSearchCount();
  }
  const appointmentForm = document.getElementById("appointmentForm");
  const appointmentModal = document.getElementById("appointmentModal");
  const closeAppointment = () => { if (appointmentModal) appointmentModal.hidden = true; };
  if (appointmentForm && appointmentModal) {
    const dateInput = document.getElementById("appointmentDate");
    if (dateInput) {
      const today = new Date();
      const localDate = new Date(today.getTime() - today.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
      dateInput.min = localDate;
    }
    appointmentForm.addEventListener("submit", event => {
      event.preventDefault();
      const name = document.getElementById("appointmentName").value.trim();
      const service = document.getElementById("appointmentService").value;
      const date = document.getElementById("appointmentDate").value;
      const lang = document.getElementById("languageSelect")?.value || "en";
      const message = document.getElementById("appointmentConfirmationText");
      if (message) {
        message.textContent = lang === "hi"
          ? `${name}, ${service} के लिए ${date} की डेमो अनुरोध दर्ज हुई। कोई वास्तविक अपॉइंटमेंट बुक नहीं हुआ।`
          : lang === "mr"
          ? `${name}, ${service} साठी ${date} ची डेमो विनंती नोंदली. प्रत्यक्ष अपॉइंटमेंट बुक झालेली नाही.`
          : `${name}, your demo request for ${service} on ${date} has been recorded on this page only. No real appointment was booked.`;
      }
      appointmentModal.hidden = false;
    });
    document.getElementById("closeAppointmentModal")?.addEventListener("click", closeAppointment);
    document.getElementById("confirmAppointmentClose")?.addEventListener("click", closeAppointment);
    appointmentModal.addEventListener("click", event => { if (event.target === appointmentModal) closeAppointment(); });
    document.addEventListener("keydown", event => { if (event.key === "Escape") closeAppointment(); });
  }
  const form = document.getElementById("contactForm");
  if (form) form.addEventListener("submit", event => {
    event.preventDefault();
    const lang = document.getElementById("languageSelect")?.value || "en";
    const status = document.getElementById("formStatus");
    status.textContent = lang === "hi" ? "धन्यवाद! यह डेमो फ़ॉर्म है; आपका संदेश भेजा या सहेजा नहीं गया।" : lang === "mr" ? "धन्यवाद! हा डेमो फॉर्म आहे; आपला संदेश पाठवला किंवा जतन केला नाही." : "Thank you! This is a demo form; your message was not sent or stored.";
    form.reset();
  });
});